In [3]:
import pandas as pd
df=pd.read_csv('customer_shopping_behavior.csv')

In [6]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [10]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [11]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [18]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [20]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [12]:
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(' ','_')
df=df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [13]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [14]:
labels=['Young Adult','Adult','Middle_age','Senior']
df['age_group']=pd.qcut(df['age'],q=4,labels=labels)

In [15]:
df[['age','age_group']].head(10)

   age    age_group
0   55   Middle_age
1   19  Young Adult
2   50   Middle_age
3   21  Young Adult
4   45   Middle_age
5   46   Middle_age
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57   Middle_age

In [16]:
frequency_mapping={
    'Fortnightly':14,
    'Weekly':7,
    'Monthly':30,
    'Quarterly':90,
    'Bi-Weekly':14,
    'Annually':365,
    'Every 3 Months':90
}

In [40]:
df['purchase_frequency_day']=df['frequency_of_purchases'].map(frequency_mapping)

In [41]:
df[['purchase_frequency_day','frequency_of_purchases']].head(10)

   purchase_frequency_day frequency_of_purchases
0                      14            Fortnightly
1                      14            Fortnightly
2                       7                 Weekly
3                       7                 Weekly
4                     365               Annually
5                       7                 Weekly
6                      90              Quarterly
7                       7                 Weekly
8                     365               Annually
9                      90              Quarterly

In [45]:
df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [46]:
(df['discount_applied']==df['promo_code_used']).all()

np.True_

In [47]:
df=df.drop('promo_code_used',axis=1)

In [48]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_day'],
      dtype='object')

In [49]:
!pip install pymysql sqlalchemy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pymysql in c:\users\user\appdata\roaming\python\python313\site-packages (1.1.2)
Requirement already satisfied: sqlalchemy in h:\conda python\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in h:\conda python\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in h:\conda python\lib\site-packages (from sqlalchemy) (4.15.0)

In [7]:
pip install psycopg2-binary

Defaulting to user installation because normal site-packages is not writeable
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp313-cp313-win_amd64.whl.metadata (5.1 kB)
Downloading psycopg2_binary-2.9.11-cp313-cp313-win_amd64.whl (2.7 MB)
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   ----------- ---------------------------- 0.8/2.7 MB 3.4 MB/s eta 0:00:01
   -------------------------------------- - 2.6/2.7 MB 6.2 MB/s eta 0:00:01
   ---------------------------------------- 2.7/2.7 MB 5.8 MB/s  0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11
Note: you may need to restart the kernel to use updated packages.

In [17]:
from sqlalchemy import create_engine

username = "postgres"
password = "0000"
host = "localhost"
port = "5432"
database = "customer_behavior"

engine = create_engine(
    f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}",
    pool_pre_ping=True,
    pool_recycle=3600
)

# Write DataFrame
df.to_sql(
    "customer",
    engine,
    if_exists="replace",
    index=False,
    chunksize=1000
)

# Read sample
import pandas as pd
pd.read_sql("SELECT * FROM customer LIMIT 5;", engine)

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases,age_group
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly,Middle_age
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly,Young Adult
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly,Middle_age
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly,Young Adult
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually,Middle_age

In [21]:
# Q1. What is the total revenue generated by male vs. female customers?

sql='''select gender, SUM(purchase_amount) as revenue
from customer
group by gender'''
pd.read_sql(sql, engine)

   gender   revenue
0  Female   75191.0
1    Male  157890.0

In [22]:
# --Q2. Which customers used a discount but still spent more than the average purchase amount? 
sql='''select customer_id, purchase_amount 
from customer 
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)'''
pd.read_sql(sql, engine)

     customer_id  purchase_amount
0              2               64
1              3               73
2              4               90
3              7               85
4              9               97
..           ...              ...
834         1667               64
835         1671               73
836         1673               73
837         1674               62
838         1676               90

[839 rows x 2 columns]

In [23]:
# -- Q3. Which are the top 5 products with the highest average review rating?
sql='''select item_purchased, round(avg(review_rating::numeric),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5'''
pd.read_sql(sql, engine)

  item_purchased  Average Product Rating
0         Gloves                    3.86
1        Sandals                    3.84
2          Boots                    3.82
3            Hat                    3.80
4          Skirt                    3.79

In [24]:
# --Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
sql='''select shipping_type, 
ROUND(AVG(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;'''
pd.read_sql(sql, engine)

  shipping_type  round
0      Standard  58.46
1       Express  60.48

In [26]:
#5. Examine whether subscribed customers spend more than non-subscribed customers by comparing their average purchase amount 
# and total revenue contribution.
sql='''SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount),2) AS avg_spend,
       ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue,avg_spend DESC;'''
pd.read_sql(sql, engine)

  subscription_status  total_customers  avg_spend  total_revenue
0                 Yes             1053      59.49        62645.0
1                  No             2847      59.87       170436.0

In [28]:
# --Q6. Which 5 products have the highest percentage of purchases with discounts applied?
sql='''SELECT item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;'''
pd.read_sql(sql, engine)

  item_purchased  discount_rate
0            Hat          50.00
1       Sneakers          49.66
2           Coat          49.07
3        Sweater          48.17
4          Pants          47.37

In [29]:
# /*--Q7. Segment customers into New, Returning, and Loyal based on their total 
# -- number of previous purchases, and show the count of each segment.*/ 
sql='''with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer)

select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;'''
pd.read_sql(sql, engine)

  customer_segment  Number of Customers
0            Loyal                 3116
1              New                   83
2        Returning                  701

In [30]:
# --Q8. What are the top 3 most purchased products within each category? 
sql='''WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;'''
pd.read_sql(sql, engine)

    item_rank     category item_purchased  total_orders
0           1  Accessories        Jewelry           171
1           2  Accessories     Sunglasses           161
2           3  Accessories           Belt           161
3           1     Clothing         Blouse           171
4           2     Clothing          Pants           171
5           3     Clothing          Shirt           169
6           1     Footwear        Sandals           160
7           2     Footwear          Shoes           150
8           3     Footwear       Sneakers           145
9           1    Outerwear         Jacket           163
10          2    Outerwear           Coat           161

In [31]:
# --Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
sql='''SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;'''
pd.read_sql(sql, engine)

  subscription_status  repeat_buyers
0                  No           2518
1                 Yes            958

In [34]:
# --Q10. What is the revenue contribution of each age group? 
sql='''SELECT 
    Age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue desc;'''
pd.read_sql(sql, engine)

     age_group  total_revenue
0  Young Adult        62143.0
1   Middle_age        59197.0
2        Adult        55978.0
3       Senior        55763.0